from __future__ import annotations
from datetime import datetime
from typing import Any
from pgvector.sqlalchemy import Vector
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Index, Integer, JSON, String, Table, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.database import Base
user_teams=Table("user_teams",Base.metadata,Column("user_id",ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),Column("team_id",ForeignKey("teams.id",ondelete="CASCADE"),primary_key=True))
document_tags=Table("document_tags",Base.metadata,Column("document_id",ForeignKey("documents.id",ondelete="CASCADE"),primary_key=True),Column("tag_id",ForeignKey("tags.id",ondelete="CASCADE"),primary_key=True))
document_teams=Table("document_teams",Base.metadata,Column("document_id",ForeignKey("documents.id",ondelete="CASCADE"),primary_key=True),Column("team_id",ForeignKey("teams.id",ondelete="CASCADE"),primary_key=True))
class User(Base):
 __tablename__="users"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(150)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); is_active:Mapped[bool]=mapped_column(Boolean,default=True); password_hash:Mapped[str|None]=mapped_column(String(255)); password_changed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); last_login_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
 teams:Mapped[list[Team]]=relationship(secondary=user_teams,back_populates="users"); uploaded_documents:Mapped[list[Document]]=relationship(back_populates="uploader"); events:Mapped[list[DocumentEvent]]=relationship(back_populates="user"); sessions:Mapped[list[UserSession]]=relationship(back_populates="user",cascade="all, delete-orphan")
class UserSession(Base):
 __tablename__="user_sessions"; __table_args__=(UniqueConstraint("token_hash",name="uq_user_sessions_token_hash"),Index("ix_user_sessions_token_hash","token_hash"),Index("ix_user_sessions_user_id","user_id"),Index("ix_user_sessions_expires_at","expires_at"))
 id:Mapped[int]=mapped_column(primary_key=True); token_hash:Mapped[str]=mapped_column(String(64),nullable=False); user_id:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),nullable=False); csrf_token_hash:Mapped[str]=mapped_column(String(64),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,server_default=func.now()); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,server_default=func.now()); revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
 user:Mapped[User]=relationship(back_populates="sessions")
class Team(Base):
 __tablename__="teams"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(150),unique=True); description:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
 users:Mapped[list[User]]=relationship(secondary=user_teams,back_populates="teams"); documents:Mapped[list[Document]]=relationship(secondary=document_teams,back_populates="teams")
class Classification(Base):
 __tablename__="classifications"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(100),unique=True); description:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); documents:Mapped[list[Document]]=relationship(back_populates="classification")
class Tag(Base):
 __tablename__="tags"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(100),unique=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); documents:Mapped[list[Document]]=relationship(secondary=document_tags,back_populates="tags")
class Document(Base):
 __tablename__="documents"; id:Mapped[int]=mapped_column(primary_key=True); filename:Mapped[str]=mapped_column(String(255)); file_path:Mapped[str]=mapped_column(String(1024),unique=True); file_type:Mapped[str]=mapped_column(String(50)); file_size:Mapped[int]=mapped_column(Integer); page_count:Mapped[int|None]=mapped_column(Integer); classification_id:Mapped[int]=mapped_column(ForeignKey("classifications.id",ondelete="RESTRICT")); uploaded_by:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT")); uploaded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); processing_status:Mapped[str]=mapped_column(String(30),nullable=False,default="uploaded",server_default="uploaded"); processing_started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); processed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); extracted_text_length:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); text_page_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); image_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); ocr_page_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); processing_error:Mapped[str|None]=mapped_column(Text); chunking_status:Mapped[str]=mapped_column(String(30),nullable=False,default="pending",server_default="pending"); chunked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); chunk_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); chunking_error:Mapped[str|None]=mapped_column(Text); chunking_version:Mapped[str|None]=mapped_column(String(50)); embedding_status:Mapped[str]=mapped_column(String(30),nullable=False,default="pending",server_default="pending"); embedded_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); embedding_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0,server_default="0"); embedding_error:Mapped[str|None]=mapped_column(Text); embedding_version:Mapped[str|None]=mapped_column(String(100))
 classification:Mapped[Classification]=relationship(back_populates="documents"); uploader:Mapped[User]=relationship(back_populates="uploaded_documents"); tags:Mapped[list[Tag]]=relationship(secondary=document_tags,back_populates="documents"); teams:Mapped[list[Team]]=relationship(secondary=document_teams,back_populates="documents"); events:Mapped[list[DocumentEvent]]=relationship(back_populates="document",cascade="all, delete-orphan"); pages:Mapped[list[DocumentPage]]=relationship(back_populates="document",cascade="all, delete-orphan",order_by="DocumentPage.page_number"); chunks:Mapped[list[DocumentChunk]]=relationship(back_populates="document",cascade="all, delete-orphan")
class DocumentEvent(Base):
 __tablename__="document_events"; id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int]=mapped_column(ForeignKey("documents.id",ondelete="CASCADE"),index=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT")); event_type:Mapped[str]=mapped_column(String(100)); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); event_metadata:Mapped[dict[str,Any]|None]=mapped_column("metadata",JSON)
 document:Mapped[Document]=relationship(back_populates="events"); user:Mapped[User]=relationship(back_populates="events")
class DocumentPage(Base):
 __tablename__="document_pages"; __table_args__=(UniqueConstraint("document_id","page_number",name="uq_document_pages_document_page"),)
 id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int]=mapped_column(ForeignKey("documents.id",ondelete="CASCADE"),nullable=False,index=True); page_number:Mapped[int]=mapped_column(Integer,nullable=False); extracted_text:Mapped[str|None]=mapped_column(Text); has_text:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False); image_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0); ocr_used:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
 document:Mapped[Document]=relationship(back_populates="pages"); chunks:Mapped[list[DocumentChunk]]=relationship(back_populates="page",cascade="all, delete-orphan",order_by="DocumentChunk.chunk_index")
class DocumentChunk(Base):
 __tablename__="document_chunks"; __table_args__=(UniqueConstraint("page_id","chunk_index",name="uq_document_chunks_page_index"),Index("ix_document_chunks_document_page","document_id","page_id"))
 id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int]=mapped_column(ForeignKey("documents.id",ondelete="CASCADE"),nullable=False,index=True); page_id:Mapped[int]=mapped_column(ForeignKey("document_pages.id",ondelete="CASCADE"),nullable=False,index=True); chunk_index:Mapped[int]=mapped_column(Integer,nullable=False); text:Mapped[str]=mapped_column(Text,nullable=False); character_count:Mapped[int]=mapped_column(Integer,nullable=False); token_count:Mapped[int|None]=mapped_column(Integer); source_start_char:Mapped[int]=mapped_column(Integer,nullable=False); source_end_char:Mapped[int]=mapped_column(Integer,nullable=False); chunk_metadata:Mapped[dict[str,Any]|None]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
 document:Mapped[Document]=relationship(back_populates="chunks"); page:Mapped[DocumentPage]=relationship(back_populates="chunks"); embeddings:Mapped[list[DocumentChunkEmbedding]]=relationship(back_populates="chunk",cascade="all, delete-orphan")
class DocumentChunkEmbedding(Base):
 __tablename__="document_chunk_embeddings"; __table_args__=(UniqueConstraint("chunk_id","embedding_version",name="uq_chunk_embeddings_chunk_version"),Index("ix_chunk_embeddings_version_chunk","embedding_version","chunk_id"),Index("ix_chunk_embeddings_embedding_hnsw","embedding",postgresql_using="hnsw",postgresql_ops={"embedding":"vector_cosine_ops"}))
 id:Mapped[int]=mapped_column(primary_key=True); chunk_id:Mapped[int]=mapped_column(ForeignKey("document_chunks.id",ondelete="CASCADE"),nullable=False,index=True); embedding:Mapped[list[float]]=mapped_column(Vector(384),nullable=False); embedding_model:Mapped[str]=mapped_column(String(255),nullable=False); embedding_version:Mapped[str]=mapped_column(String(100),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
 chunk:Mapped[DocumentChunk]=relationship(back_populates="embeddings")
